default:
  user: monitoring@pve
  password: CHANGE_ME_TO_YOUR_ACTUAL_PASSWORD
  verify_ssl: false
  target: CHANGE_ME_TO_YOUR_PROXMOX_HOST
  port: 8006
# Example configuration for Proxmox VE exporter
# Replace with your actual Proxmox credentials and settings

# Multiple PVE nodes can be configured like this:
# pve1:
#   user: monitoring@pve
#   password: password1
#   verify_ssl: false
#
# pve2:
#   user: monitoring@pve
#   password: password2
#   verify_ssl: false
