name: infra-client

services:
  portainer-agent:
    image: portainer/agent:latest
    container_name: portainer-agent
    hostname: mobydick-agent
    restart: unless-stopped
    ports:
      - "10.10.1.30:9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - TZ=America/Sao_Paulo
    labels:
      - com.centurylinklabs.watchtower.enable=true

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_SCHEDULE=0 0 5 * * *
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_TOKEN:-watchtower-secret}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - com.centurylinklabs.watchtower.enable=true

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    user: "0:0"
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --disable-reporting
      - /etc/alloy/mobydick/alloy.hcl
    volumes:
      - /:/host:ro,rslave
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/var/log:ro
      - ../lgtm:/etc/alloy:ro
      - /run/udev:/run/udev:ro
    ports:
      - "10.10.1.30:12345:12345"
    environment:
      - TZ=America/Sao_Paulo
      - WATCHTOWER_TOKEN=${WATCHTOWER_TOKEN:-watchtower-secret}
    labels:
      - com.centurylinklabs.watchtower.enable=true
