name: media-client
version: "3.9"

x-common-env: &common-env
  TZ: America/Sao_Paulo

services:
  # plex:
  #   image: plexinc/pms-docker:latest
  #   container_name: plex
  #   restart: unless-stopped
  #   network_mode: host
  #   environment:
  #     <<: *common-env
  #     PLEX_UID: 1000
  #     PLEX_GID: 1000
  #   init: true
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu, compute, video, utility]
  #   devices:
  #     - /dev/dri:/dev/dri
  #     - /dev/bus/usb:/dev/bus/usb:rw
  #   device_cgroup_rules:
  #     - "c 189:* rmw"
  #     - "c 226:* rmw"
  #   volumes:
  #     - /srv/media/plex/config:/config:rw
  #     - /srv/media/plex/transcode:/transcode:rw
  #     - /mnt/sokolov/media/Videos/radarr/movies:/data/movies:ro
  #     - /mnt/sokolov/media/Videos/radarr/animes:/data/animes:ro
  #     - /mnt/sokolov/media/Videos/sonarr/series:/data/series:ro
  #   healthcheck:
  #     test:
  #       ["CMD-SHELL", "curl -fsS http://127.0.0.1:32400/identity > /dev/null || exit 1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 10
  #     start_period: 120s
  #   stop_grace_period: 30s
  #   stop_signal: SIGTERM
  #   labels:
  #     - com.centurylinklabs.watchtower.enable=true

  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      <<: *common-env
      PLEX_UID: 1000
      PLEX_GID: 1000
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
    gpus: all
    # runtime: nvidia
    volumes:
      - /srv/media/plex/config:/config:rw
      - /srv/media/plex/transcode:/transcode:rw
      - /mnt/sokolov/media/Videos/radarr/movies:/data/movies:ro
      - /mnt/sokolov/media/Videos/radarr/animes:/data/animes:ro
      - /mnt/sokolov/media/Videos/sonarr/series:/data/series:ro
    devices:
      - /dev/bus/usb:/dev/bus/usb:rw
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://127.0.0.1:32400/identity >/dev/null || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s
    labels:
      - com.centurylinklabs.watchtower.enable=true

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    network_mode: host
    environment:
      <<: *common-env
      PUID: 1000
      PGID: 1000
    volumes:
      - /srv/media/tautulli/config:/config:rw
      - "/srv/media/plex/config/Library/Application Support/Plex Media Server/Logs:/logs:ro"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://127.0.0.1:8181/status >/dev/null || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 40s
    stop_grace_period: 10s
    stop_signal: SIGTERM
    depends_on:
      plex:
        condition: service_healthy
    labels:
      - com.centurylinklabs.watchtower.enable=true
