name: homepage

networks:
  proxy:
    external: true

services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /srv/homarr/config:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
      - DOCKER_HOSTNAMES=dockerproxy,10.10.1.30
      - DOCKER_PORTS=2375,2375
    networks: [proxy]
    labels:
      - com.centurylinklabs.watchtower.enable=true
