name: media-core

networks:
  media_net:
    name: media_net
  proxy:
    external: true

x-common-env: &common-env
  TZ: America/Sao_Paulo
  PUID: 1500
  PGID: 1500

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      <<: *common-env
      WEBUI_PORT: 8080
    ports:
      - "64385:64385"
      - "64385:64385/udp"
    volumes:
      - /srv/media/qbittorrent/config:/config:rw
      - /mnt/pve/media/Downloads/torrents:/downloads:rw
    networks: [media_net, proxy]
    labels:
      - com.centurylinklabs.watchtower.enable=true

  jackett:
    image: ghcr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    environment: *common-env
    volumes:
      - /srv/media/jackett/config:/config
    networks: [media_net, proxy]
    labels:
      - com.centurylinklabs.watchtower.enable=true

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment: *common-env
    volumes:
      - /srv/media/radarr/config:/config:rw
      - /mnt/sokolov/media/Videos/radarr/movies:/movies:rw
      - /mnt/sokolov/media/Videos/radarr/animes:/animes:rw
      - /mnt/pve/media/Downloads/torrents:/downloads:rw
    networks: [media_net, proxy]
    labels:
      - com.centurylinklabs.watchtower.enable=true

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment: *common-env
    volumes:
      - /srv/media/sonarr/config:/config:rw
      - /mnt/sokolov/media/Videos/sonarr/series:/series:rw
      - /mnt/sokolov/media/Videos/radarr/animes:/animes:rw
      - /mnt/pve/media/Downloads/torrents:/downloads:rw
    networks: [media_net, proxy]
    labels:
      - com.centurylinklabs.watchtower.enable=true

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment: *common-env
    volumes:
      - /srv/media/prowlarr/config:/config:rw
    networks: [media_net, proxy]
    labels:
      - com.centurylinklabs.watchtower.enable=true

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment: *common-env
    volumes:
      - /srv/media/bazarr/config:/config:rw
      - /mnt/sokolov/media/Videos/radarr/movies:/movies:rw
      - /mnt/sokolov/media/Videos/radarr/animes:/animes:rw
      - /mnt/sokolov/media/Videos/sonarr/series:/series:rw
    networks: [media_net, proxy]
    labels:
      - com.centurylinklabs.watchtower.enable=true

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    environment:
      <<: *common-env
      LOG_LEVEL: info
    volumes:
      - /srv/media/overseerr/config:/app/config:rw
    networks: [media_net, proxy]
    labels:
      - com.centurylinklabs.watchtower.enable=true

  kavita:
    image: kizaing/kavita:latest
    container_name: kavita
    restart: unless-stopped
    volumes:
      - /mnt/sokolov/media/Books:/data/books:ro
      - /srv/media/kavita/config:/kavita/config:rw
    networks: [media_net, proxy]
    labels:
      - com.centurylinklabs.watchtower.enable=true

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: unless-stopped
    environment:
      <<: *common-env
      DOCKER_MODS: linuxserver/mods:universal-calibre
    volumes:
      - /srv/media/calibre-web/config:/config:rw
      - /mnt/sokolov/media/Books/calibre:/books:rw
    networks: [media_net, proxy]
    labels:
      - com.centurylinklabs.watchtower.enable=true

  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    restart: unless-stopped
    environment: *common-env
    volumes:
      - /srv/media/lazylibrarian/config:/config:rw
      - /mnt/pve/media/Downloads/torrents:/downloads:rw
      - /mnt/sokolov/media/Books/calibre:/books:rw
    networks: [media_net, proxy]
    labels:
      - com.centurylinklabs.watchtower.enable=true

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      <<: *common-env
      LOG_LEVEL: info
      LOG_HTML: false
      CAPTCHA_SOLVER: none
    volumes:
      - /srv/media/flaresolverr/config:/config:rw
    networks: [media_net, proxy]
    labels:
      - com.centurylinklabs.watchtower.enable=true

  ocrmypdf:
    image: jbarlow83/ocrmypdf
    container_name: ocrmypdf
    restart: unless-stopped
    command:
      [
        "--watch",
        "/input",
        "/output",
        "--output-type",
        "pdfa",
        "--optimize",
        "3",
        "--language",
        "eng",
      ]
    volumes:
      - /mnt/sokolov/media/Books/inbox/raw:/input:rw
      - /mnt/sokolov/media/Books/inbox/processed:/output:rw
    networks: [media_net]
    labels:
      - com.centurylinklabs.watchtower.enable=true
