name: media-client

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
      # - PLEX_CLAIM=${PLEX_CLAIM}   # optional: plex.tv claim
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
    volumes:
      - ${CFG_PATH}/plex:/config:rw
      - ${FAST_PATH}/transcode:/transcode:rw
      - /mnt/sokolov/media/Videos/radarr/movies:/movies:ro
      - /mnt/sokolov/media/Videos/radarr/animes:/animes:ro
      - /mnt/sokolov/media/Videos/sonarr/series:/series:ro
