name: media-reader

networks:
  media_net:
    external: true

x-common-env: &common-env
  TZ: America/Sao_Paulo
  PUID: 1500
  PGID: 1500

services:
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    restart: unless-stopped
    volumes:
      - /mnt/sokolov/media/Books:/data/books:ro
      - /srv/media/kavita/config:/kavita/config:rw
    networks:
      - media_net
    labels:
      - com.centurylinklabs.watchtower.enable=true

  booklore:
    image: booklore/booklore:latest
    container_name: booklore
    restart: unless-stopped
    environment:
      <<: *common-env
      DATABASE_URL: ${DB_BOOKLORE_URL}
      DATABASE_USERNAME: ${DB_BOOKLORE_USER}
      DATABASE_PASSWORD: ${DB_BOOKLORE_PASSWORD}
      BOOKLORE_PORT: 3211
    networks:
      - media_net
    volumes:
      - /srv/media/booklore/data:/app/data:rw
      - /mnt/sokolov/media/Books:/books:rw
      - /srv/media/booklore/bookdrop:/bookdrop:rw
    labels:
      - com.centurylinklabs.watchtower.enable=true

  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    restart: unless-stopped
    environment:
      <<: *common-env
      DOCKER_MODS: linuxserver/mods:lazylibrarian-ffmpeg
    volumes:
      - /srv/media/lazylibrarian/config:/config:rw
      - /mnt/sokolov/media/Books:/books:rw
      - /mnt/pve/media/Downloads/torrents:/downloads:rw
    networks:
      - media_net
    labels:
      - com.centurylinklabs.watchtower.enable=true

  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    restart: unless-stopped
    environment:
      <<: *common-env
      PASSWORD: ${CALIBRE_PASSWORD:-password}
    volumes:
      - /srv/media/calibre/config:/config:rw
      - /mnt/sokolov/media/Books:/books:rw
    networks:
      - media_net
    labels:
      - com.centurylinklabs.watchtower.enable=true

  kapowarr:
    image: mrcas/kapowarr:latest
    container_name: kapowarr
    restart: unless-stopped
    environment:
      <<: *common-env
    volumes:
      - /srv/media/kapowarr/db:/app/db:rw
      - /mnt/sokolov/media/Comics:/comics:rw
      - /mnt/pve/media/Downloads/torrents:/app/temp_downloads:rw
    networks:
      - media_net
    labels:
      - com.centurylinklabs.watchtower.enable=true
