name: media-core

networks:
  media_net:
    name: media_net
  proxy:
    external: true
  core_macvlan:
    name: core_macvlan
    driver: macvlan
    driver_opts:
      parent: ${MACVLAN_INTERFACE:-eth0}
    ipam:
      config:
        - subnet: 10.10.1.0/24
          gateway: 10.10.1.1
          ip_range: 10.10.1.100/32

x-common-env: &common-env
  TZ: America/Sao_Paulo
  PUID: 1500
  PGID: 1500

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      <<: *common-env
      WEBUI_PORT: 8080
    volumes:
      - /srv/media/qbittorrent/config:/config:rw
      - /mnt/pve/media/Downloads/torrents:/downloads:rw
    networks:
      core_macvlan:
        ipv4_address: 10.10.1.100
      media_net:
      proxy:
    labels:
      - com.centurylinklabs.watchtower.enable=true

  jackett:
    image: ghcr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    environment: *common-env
    volumes:
      - /srv/media/jackett/config:/config
    networks: [media_net, proxy]
    labels:
      - com.centurylinklabs.watchtower.enable=true

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment: *common-env
    volumes:
      - /srv/media/radarr/config:/config:rw
      - /mnt/sokolov/media/Videos/radarr/movies:/movies:rw
      - /mnt/sokolov/media/Videos/radarr/animes:/animes:rw
      - /mnt/pve/media/Downloads/torrents:/downloads:rw
    networks: [media_net, proxy]
    labels:
      - com.centurylinklabs.watchtower.enable=true

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment: *common-env
    volumes:
      - /srv/media/sonarr/config:/config:rw
      - /mnt/sokolov/media/Videos/sonarr/series:/series:rw
      - /mnt/sokolov/media/Videos/radarr/animes:/animes:rw
      - /mnt/pve/media/Downloads/torrents:/downloads:rw
    networks: [media_net, proxy]
    labels:
      - com.centurylinklabs.watchtower.enable=true

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment: *common-env
    volumes:
      - /srv/media/prowlarr/config:/config:rw
    networks: [media_net, proxy]
    labels:
      - com.centurylinklabs.watchtower.enable=true

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment: *common-env
    volumes:
      - /srv/media/bazarr/config:/config:rw
      - /mnt/sokolov/media/Videos/radarr/movies:/movies:rw
      - /mnt/sokolov/media/Videos/radarr/animes:/animes:rw
      - /mnt/sokolov/media/Videos/sonarr/series:/series:rw
    networks: [media_net, proxy]
    labels:
      - com.centurylinklabs.watchtower.enable=true

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    environment:
      <<: *common-env
      LOG_LEVEL: info
    volumes:
      - /srv/media/overseerr/config:/app/config:rw
    networks: [media_net, proxy]
    labels:
      - com.centurylinklabs.watchtower.enable=true

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      <<: *common-env
      LOG_LEVEL: info
      LOG_HTML: false
      CAPTCHA_SOLVER: none
    volumes:
      - /srv/media/flaresolverr/config:/config:rw
    networks: [media_net, proxy]
    labels:
      - com.centurylinklabs.watchtower.enable=true

  profilarr:
    image: santiagosayshey/profilarr:latest
    container_name: profilarr
    restart: unless-stopped
    environment:
      <<: *common-env
    volumes:
      - /srv/media/profilarr/config:/config:rw
    networks: [media_net, proxy]
    labels:
      - com.centurylinklabs.watchtower.enable=true

  huntarr:
    image: huntarr/huntarr:latest
    container_name: huntarr
    restart: unless-stopped
    environment:
      <<: *common-env
    volumes:
      - /srv/media/huntarr:/config:rw
    networks: [media_net, proxy]
    labels:
      - com.centurylinklabs.watchtower.enable=true

  cleanuparr:
    image: ghcr.io/cleanuparr/cleanuparr:latest
    container_name: cleanuparr
    restart: unless-stopped
    environment:
      <<: *common-env
      PORT: 11011
    volumes:
      - /srv/media/cleanuparr/config:/config:rw
    networks: [media_net, proxy]
    labels:
      - com.centurylinklabs.watchtower.enable=true
