name: games

networks:
  games_net:
    name: games_net

volumes:
  romm_mysql_data:
  romm_resources:
  romm_redis_data:

x-common-env: &common-env
  TZ: America/Sao_Paulo
  PUID: 1500
  PGID: 1500

services:
  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    environment:
      <<: *common-env
      DB_HOST: romm-db
      DB_NAME: romm
      DB_USER: romm-user
      DB_PASSWD: ${ROMM_DB_PASSWORD:?ROMM_DB_PASSWORD not set}
      ROMM_AUTH_SECRET_KEY: ${ROMM_AUTH_SECRET_KEY:?ROMM_AUTH_SECRET_KEY not set}
      IGDB_CLIENT_ID: ${IGDB_CLIENT_ID:-}
      IGDB_CLIENT_SECRET: ${IGDB_CLIENT_SECRET:-}
      SCREENSCRAPER_USER: ${SCREENSCRAPER_USER:-}
      SCREENSCRAPER_PASSWORD: ${SCREENSCRAPER_PASSWORD:-}
      RETROACHIEVEMENTS_USERNAME: ${RETROACHIEVEMENTS_USERNAME:-}
      RETROACHIEVEMENTS_API_KEY: ${RETROACHIEVEMENTS_API_KEY:-}
      # MOBYGAMES_API_KEY: ${MOBYGAMES_API_KEY:-}
      STEAMGRIDDB_API_KEY: ${STEAMGRIDDB_API_KEY:-}
      HASHEOUS_API_ENABLED: true
      PLAYMATCH_API_ENABLED: true
      LAUNCHBOX_API_ENABLED: true
    volumes:
      - romm_resources:/romm/resources
      - romm_redis_data:/redis-data
      - /mnt/sokolov/media/Games/roms:/romm/library:rw
      - /srv/games/romm/assets:/romm/assets:rw
      - /srv/games/romm/config:/romm/config:rw
    ports:
      - 8383:8080
    networks: [games_net]
    depends_on:
      romm-db:
        condition: service_healthy
        restart: true
    labels:
      - com.centurylinklabs.watchtower.enable=true

  romm-db:
    image: mariadb:latest
    container_name: romm-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${ROMM_DB_ROOT_PASSWORD:?ROMM_DB_ROOT_PASSWORD not set}
      MARIADB_DATABASE: romm
      MARIADB_USER: romm-user
      MARIADB_PASSWORD: ${ROMM_DB_PASSWORD:?ROMM_DB_PASSWORD not set}
    volumes:
      - romm_mysql_data:/var/lib/mysql
    networks: [games_net]
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - com.centurylinklabs.watchtower.enable=true
