name: media-client

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=America/Sao_Paulo
      - PLEX_UID=1000
      - PLEX_GID=1000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video, utility]
    devices:
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb:rw
    device_cgroup_rules:
      - "c 189:* rmw"
      - "c 226:* rmw"
    volumes:
      - /srv/media/plex/config:/config:rw
      - /srv/media/plex/transcode:/transcode:rw
      - /mnt/sokolov/media/Videos/radarr/movies:/data/movies:ro
      - /mnt/sokolov/media/Videos/radarr/animes:/data/animes:ro
      - /mnt/sokolov/media/Videos/sonarr/series:/data/series:ro

  handbrake:
    image: jlesage/handbrake:latest
    container_name: handbrake
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - USER_ID=1000
      - GROUP_ID=1000
      - KEEP_APP_RUNNING=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video, utility]
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /srv/media/handbrake/config:/config:rw
      - /mnt/sokolov/media/Videos:/storage:ro
      - /srv/media/handbrake/watch:/watch:rw
      - /srv/media/handbrake/output:/output:rw
    ports:
      - "5800:5800"
    labels:
      - com.centurylinklabs.watchtower.enable=true
