name: media-reader

networks:
  media_net:
    external: true

x-common-env: &common-env
  TZ: America/Sao_Paulo
  PUID: 1500
  PGID: 1500

services:
  kavita:
    image: kizaing/kavita:latest
    container_name: kavita
    restart: unless-stopped
    volumes:
      - /mnt/sokolov/media/Books:/data/books:ro
      - /srv/media/kavita/config:/kavita/config:rw
    networks:
      - media_net
    labels:
      - com.centurylinklabs.watchtower.enable=true

  booklore:
    image: booklore/booklore:latest
    container_name: booklore
    restart: unless-stopped
    environment:
      <<: *common-env
      DATABASE_URL: jdbc:mariadb://npm:3306/booklore
      DATABASE_USERNAME: booklore
      DATABASE_PASSWORD: ${DB_BOOKLORE_PASSWORD}
      BOOKLORE_PORT: 3211
    networks:
      - media_net
    volumes:
      - /srv/media/booklore/data:/app/data:rw
      - /mnt/sokolov/media/Books:/books:rw
      - /srv/media/booklore/bookdrop:/bookdrop:rw
    labels:
      - com.centurylinklabs.watchtower.enable=true

  readarr:
    image: ghcr.io/hotio/readarr
    container_name: readarr
    restart: unless-stopped
    environment:
      <<: *common-env
    volumes:
      - /srv/media/readarr/config:/config:rw
      - /mnt/sokolov/media/Books:/books:rw
      - /mnt/pve/media/Downloads/torrents:/downloads:rw
    networks:
      - media_net
    labels:
      - com.centurylinklabs.watchtower.enable=true

  rreading-glasses:
    image: blampe/rreading-glasses:hardcover
    container_name: rreading-glasses
    restart: unless-stopped
    entrypoint: ["/main", "serve"]
    command:
      - --verbose
    mem_limit: 128m
    environment:
      HARDCOVER_AUTH: ${HARDCOVER_TOKEN}
      POSTGRES_HOST: npm
      POSTGRES_DATABASE: rreading_glasses
      POSTGRES_USER: rg
      POSTGRES_PASSWORD: ${DB_RREADING_GLASSES_PASSWORD}
    networks:
     - media_net
    labels:
      - com.centurylinklabs.watchtower.enable=true

  kapowarr:
    image: mrcas/kapowarr:latest
    container_name: kapowarr
    restart: unless-stopped
    environment:
      <<: *common-env
    volumes:
      - /srv/media/kapowarr/db:/app/db:rw
      - /mnt/sokolov/media/Comics:/comics:rw
      - /mnt/pve/media/Downloads/torrents:/app/temp_downloads:rw
    networks:
      - media_net
    labels:
      - com.centurylinklabs.watchtower.enable=true
