name: media-client

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: always
    network_mode: host
    environment:
      - TZ=America/Sao_Paulo
      - PLEX_UID=1000
      - PLEX_GID=1000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video, utility]
    devices:
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb:rw
    device_cgroup_rules:
      - "c 189:* rmw"
      - "c 226:* rmw"
    volumes:
      - /srv/media/plex/config:/config:rw
      - /srv/media/plex/transcode:/transcode:rw
      - /mnt/sokolov/media/Videos/radarr/movies:/data/movies:ro
      - /mnt/sokolov/media/Videos/radarr/animes:/data/animes:ro
      - /mnt/sokolov/media/Videos/sonarr/series:/data/series:ro
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:32400/web/index.html || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    stop_grace_period: 30s
    stop_signal: SIGTERM
    labels:
      - com.centurylinklabs.watchtower.enable=true
