name: media-client

x-common-env: &common-env
  TZ: America/Sao_Paulo

services:
  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    restart: unless-stopped
    environment:
      - AUTOHEAL_INTERVAL=30
      - AUTOHEAL_START_PERIOD=120
      - AUTOHEAL_EXITED=true
      - AUTOHEAL_CONTAINER_LABEL=autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - com.centurylinklabs.watchtower.enable=true

  preflight:
    image: alpine:latest
    container_name: preflight
    restart: "no"
    command: >
      sh -c '
        for i in $(seq 1 120); do
          test -e /dev/dri/renderD128 &&
          test -d /mnt/sokolov/media/Videos/radarr/movies &&
          test -d /mnt/sokolov/media/Videos/radarr/animes &&
          test -d /mnt/sokolov/media/Videos/sonarr/series && exit 0;
          echo "waiting for GPU/mounts..."; sleep 2;
        done; exit 1'
    volumes:
      - /dev/dri:/dev/dri
      - /mnt/sokolov/media:/mnt/sokolov/media:ro

  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      <<: *common-env
      PLEX_UID: 1000
      PLEX_GID: 1000
    init: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video, utility]
    devices:
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb:rw
    device_cgroup_rules:
      - "c 189:* rmw"
      - "c 226:* rmw"
    volumes:
      - /srv/media/plex/config:/config:rw
      - /srv/media/plex/transcode:/transcode:rw
      - /mnt/sokolov/media/Videos/radarr/movies:/data/movies:ro
      - /mnt/sokolov/media/Videos/radarr/animes:/data/animes:ro
      - /mnt/sokolov/media/Videos/sonarr/series:/data/series:ro
    healthcheck:
      test:
        ["CMD-SHELL", "curl -fsS http://127.0.0.1:32400/identity > /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s
    stop_grace_period: 30s
    stop_signal: SIGTERM
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
    depends_on:
      preflight:
        condition: service_completed_successfully

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    network_mode: host
    environment:
      <<: *common-env
      PUID: 1000
      PGID: 1000
    volumes:
      - /srv/media/tautulli/config:/config:rw
      - "/srv/media/plex/config/Library/Application Support/Plex Media Server/Logs:/logs:ro"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://127.0.0.1:8181/status >/dev/null || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 40s
    stop_grace_period: 10s
    stop_signal: SIGTERM
    depends_on:
      plex:
        condition: service_healthy
    labels:
      - com.centurylinklabs.watchtower.enable=true
