name: homepage

networks:
  proxy:
    external: true

services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    restart: unless-stopped
    environment:
      - CONTAINERS=1
      - SERVICES=1
      - TASKS=1
      - POST=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - com.centurylinklabs.watchtower.enable=true

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
      # Service Hosts (IPs or hostnames)
      - HOMEPAGE_VAR_PLEX_HOST=${PLEX_HOST:-127.0.0.1}
      - HOMEPAGE_VAR_TAUTULLI_HOST=${TAUTULLI_HOST:-127.0.0.1}
      - HOMEPAGE_VAR_MOBYDICK_HOST=${MOBYDICK_HOST}
      - HOMEPAGE_VAR_WATCHTOWER_MOBYDICK_HOST=${MOBYDICK_HOST}
      - HOMEPAGE_VAR_ROMM_HOST=${MOBYDICK_HOST}
      # Service API Keys and Credentials
      - HOMEPAGE_VAR_PLEX_API_KEY=${PLEX_API_KEY}
      - HOMEPAGE_VAR_TAUTULLI_API_KEY=${TAUTULLI_API_KEY}
      - HOMEPAGE_VAR_RADARR_API_KEY=${RADARR_API_KEY}
      - HOMEPAGE_VAR_SONARR_API_KEY=${SONARR_API_KEY}
      - HOMEPAGE_VAR_PROWLARR_API_KEY=${PROWLARR_API_KEY}
      - HOMEPAGE_VAR_BAZARR_API_KEY=${BAZARR_API_KEY}
      - HOMEPAGE_VAR_OVERSEERR_API_KEY=${OVERSEERR_API_KEY}
      - HOMEPAGE_VAR_QBITTORRENT_USERNAME=${QBITTORRENT_USERNAME}
      - HOMEPAGE_VAR_QBITTORRENT_PASSWORD=${QBITTORRENT_PASSWORD}
      - HOMEPAGE_VAR_JACKETT_API_KEY=${JACKETT_API_KEY}
      - HOMEPAGE_VAR_KAVITA_USERNAME=${KAVITA_USERNAME}
      - HOMEPAGE_VAR_KAVITA_PASSWORD=${KAVITA_PASSWORD}
      - HOMEPAGE_VAR_NPM_USERNAME=${NPM_USERNAME}
      - HOMEPAGE_VAR_NPM_PASSWORD=${NPM_PASSWORD}
      - HOMEPAGE_VAR_PORTAINER_API_KEY=${PORTAINER_API_KEY}
      - HOMEPAGE_VAR_WATCHTOWER_TOKEN=${WATCHTOWER_TOKEN}
      - HOMEPAGE_VAR_WATCHTOWER_MOBYDICK_TOKEN=${WATCHTOWER_MOBYDICK_TOKEN}
      - HOMEPAGE_VAR_GRAFANA_USER=${GRAFANA_USER}
      - HOMEPAGE_VAR_GRAFANA_PASS=${GRAFANA_PASS}
      - HOMEPAGE_VAR_N8N_HOST=${N8N_HOST}
      - HOMEPAGE_VAR_ROMM_USERNAME=${ROMM_USERNAME}
      - HOMEPAGE_VAR_ROMM_PASSWORD=${ROMM_PASSWORD}
    volumes:
      - /srv/homepage/config:/app/config:rw
      - /srv/homepage/icons:/app/public/icons:rw
      - /srv/homepage/images:/app/public/images:rw
      # Optional: Mount additional paths for disk usage widgets
      - /mnt/sokolov:/mnt/sokolov:ro
      - /mnt/pve:/mnt/pve:ro
    networks:
      - proxy
    depends_on:
      - dockerproxy
    labels:
      - com.centurylinklabs.watchtower.enable=true
