---
- Media:
    - Plex:
        icon: plex.png
        href: {{HOMEPAGE_VAR_PLEX_HOST}}
        description: Media Server
        server: mobydick
        container: plex
        widget:
          type: plex
          url: {{HOMEPAGE_VAR_PLEX_URL}}
          key: {{HOMEPAGE_VAR_PLEX_API_KEY}}

    - Tautulli:
        icon: tautulli.png
        href: {{HOMEPAGE_VAR_TAUTULLI_URL}}
        description: Plex Statistics
        server: mobydick
        container: tautulli
        widget:
          type: tautulli
          url: {{HOMEPAGE_VAR_TAUTULLI_URL}}
          key: {{HOMEPAGE_VAR_TAUTULLI_API_KEY}}

- Media Management:
    - Radarr:
        icon: radarr.png
        href: {{HOMEPAGE_VAR_RADARR_URL}}
        description: Movies Management
        server: willy
        container: radarr
        widget:
          type: radarr
          url: {{HOMEPAGE_VAR_RADARR_URL}}
          key: {{HOMEPAGE_VAR_RADARR_API_KEY}}

    - Sonarr:
        icon: sonarr.png
        href: {{HOMEPAGE_VAR_SONARR_URL}}
        description: Series Management
        server: willy
        container: sonarr
        widget:
          type: sonarr
          url: {{HOMEPAGE_VAR_SONARR_URL}}
          key: {{HOMEPAGE_VAR_SONARR_API_KEY}}

    - Prowlarr:
        icon: prowlarr.png
        href: {{HOMEPAGE_VAR_PROWLARR_URL}}
        description: Indexer Manager
        server: willy
        container: prowlarr
        widget:
          type: prowlarr
          url: {{HOMEPAGE_VAR_PROWLARR_URL}}
          key: {{HOMEPAGE_VAR_PROWLARR_API_KEY}}

    - Bazarr:
        icon: bazarr.png
        href: {{HOMEPAGE_VAR_BAZARR_URL}}
        description: Subtitles Management
        server: willy
        container: bazarr
        widget:
          type: bazarr
          url: {{HOMEPAGE_VAR_BAZARR_URL}}
          key: {{HOMEPAGE_VAR_BAZARR_API_KEY}}

    - Overseerr:
        icon: overseerr.png
        href: {{HOMEPAGE_VAR_OVERSEERR_URL}}
        description: Media Requests
        server: willy
        container: overseerr
        widget:
          type: overseerr
          url: {{HOMEPAGE_VAR_OVERSEERR_URL}}
          key: {{HOMEPAGE_VAR_OVERSEERR_API_KEY}}

    - Huntarr:
        icon: huntarr.png
        href: {{HOMEPAGE_VAR_HUNTARR_URL}}
        description: Stalled Downloads Manager
        server: willy
        container: huntarr

    - Cleanuparr:
        icon: cleanuparr.png
        href: {{HOMEPAGE_VAR_CLEANUPARR_URL}}
        description: Media Cleanup Automation
        server: willy
        container: cleanuparr

    - Profilarr:
        icon: profilarr.png
        href: {{HOMEPAGE_VAR_PROFILARR_URL}}
        description: Quality Profile Manager
        server: willy
        container: profilarr

- Downloads:
    - qBittorrent:
        icon: qbittorrent.png
        href: {{HOMEPAGE_VAR_QBITTORRENT_URL}}
        description: Torrent Client
        server: willy
        container: qbittorrent
        widget:
          type: qbittorrent
          url: {{HOMEPAGE_VAR_QBITTORRENT_URL}}
          username: {{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}
          password: {{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}

    - Jackett:
        icon: jackett.png
        href: {{HOMEPAGE_VAR_JACKETT_URL}}
        description: Indexer Proxy
        server: willy
        container: jackett
        widget:
          type: jackett
          url: {{HOMEPAGE_VAR_JACKETT_URL}}
          key: {{HOMEPAGE_VAR_JACKETT_API_KEY}}

- Infrastructure:
    - Proxmox:
        icon: proxmox.png
        href: {{HOMEPAGE_VAR_PVE_URL}}
        description: Virtualization Platform
        widget:
          type: proxmox
          url: {{HOMEPAGE_VAR_PVE_URL}}

    - Nginx Proxy Manager:
        icon: nginx-proxy-manager.png
        href: {{HOMEPAGE_VAR_NPM_URL}}
        description: Reverse Proxy
        server: willy
        container: npm
        widget:
          type: npm
          url: {{HOMEPAGE_VAR_NPM_URL}}
          username: {{HOMEPAGE_VAR_NPM_USERNAME}}
          password: {{HOMEPAGE_VAR_NPM_PASSWORD}}

    - Portainer:
        icon: portainer.png
        href: {{HOMEPAGE_VAR_PORTAINER_URL}}
        description: Container Management
        server: willy
        container: portainer
        widget:
          type: portainer
          url: {{HOMEPAGE_VAR_PORTAINER_URL}}
          env: 1
          key: {{HOMEPAGE_VAR_PORTAINER_API_KEY}}

    - Watchtower Willy:
        icon: watchtower.png
        href: {{HOMEPAGE_VAR_WATCHTOWER_WILLY_URL}}
        description: Auto Container Updates
        server: willy
        container: watchtower
        widget:
          type: watchtower
          url: {{HOMEPAGE_VAR_WATCHTOWER_WILLY_URL}}
          key: {{HOMEPAGE_VAR_WATCHTOWER_WILLY_TOKEN}}

    - Watchtower Mobydick:
        icon: watchtower.png
        href: {{HOMEPAGE_VAR_WATCHTOWER_MOBYDICK_URL}}
        description: Auto Container Updates
        server: mobydick
        container: watchtower
        widget:
          type: watchtower
          url: {{HOMEPAGE_VAR_WATCHTOWER_MOBYDICK_URL}}
          key: {{HOMEPAGE_VAR_WATCHTOWER_MOBYDICK_TOKEN}}

- Networking:
    - Pi-Hole:
        icon: pihole.png
        href: {{HOMEPAGE_VAR_PIHOLE_URL}}
        description: DNS & Ad Blocking
        proxmoxNode: {{HOMEPAGE_VAR_PVE_NODE}}
        proxmoxVMID: {{HOMEPAGE_VAR_PIHOLE_VMID}}
        proxmoxType: lxc

    - pfsense:
        icon: pfsense.png
        href: {{HOMEPAGE_VAR_PFSENSE_URL}}
        description: Firewall & Router
        proxmoxNode: {{HOMEPAGE_VAR_PVE_NODE}}
        proxmoxVMID: {{HOMEPAGE_VAR_PFSENSE_VMID}}

- Data:
    - Proxmox Backup Server:
        icon: proxmox-backup.png
        href: {{HOMEPAGE_VAR_PBS_URL}}
        description: Backup Server
        proxmoxNode: {{HOMEPAGE_VAR_PVE_NODE}}
        proxmoxVMID: {{HOMEPAGE_VAR_PBS_VMID}}
        proxmoxType: lxc

    - TrueNAS:
        icon: truenas.png
        href: {{HOMEPAGE_VAR_TRUENAS_HOST}}
        description: NAS
        proxmoxNode: {{HOMEPAGE_VAR_PVE_NODE}}
        proxmoxVMID: {{HOMEPAGE_VAR_TRUENAS_VMID}}

- Monitoring:
    - Grafana:
        icon: grafana.png
        href: {{HOMEPAGE_VAR_GRAFANA_URL}}
        description: Metrics & Logs
        server: willy
        container: lgtm
        widget:
          type: grafana
          url: {{HOMEPAGE_VAR_GRAFANA_URL}}
          username: {{HOMEPAGE_VAR_GRAFANA_USER}}
          password: {{HOMEPAGE_VAR_GRAFANA_PASS}}

- Games:
    - RomM:
        icon: romm.png
        href: {{HOMEPAGE_VAR_ROMM_URL}}
        description: ROM Manager
        server: mobydick
        container: romm
        widget:
          type: romm
          url: {{HOMEPAGE_VAR_ROMM_URL}}
          username: {{HOMEPAGE_VAR_ROMM_USERNAME}}
          password: {{HOMEPAGE_VAR_ROMM_PASSWORD}}
